# Base inference Configuration.
defaults:
  - aa

inference:
  ckpt_path: /home/afavor/git/RFD_AF/3template_na/rf_diffusion/train_session2023-11-21_1700601321.4267492/models/BFF_3.pt
  str_self_cond: True
  model_runner: NRBStyleSelfCond
  two_template: True
  three_template: True
  cautious: True
  input_pdb: /home/afavor/git/RFD_AF/inputs/DBP035.pdb
  ij_visible: null
  motif_only_2d: True
  chainbreak_chunks: True
  supply_motif_seq: True
  mask_seq_by_polymer: True
  num_atoms_modeled: 23
  num_atoms_saved: 13
  scaffold_guided: False


  # align_motif: False

preprocess:
  eye_frames: True
  num_atoms_na: 3
  motif_sidechain_input: False
  d_t2d: 72

contigmap:
  contigs: ['30']
  polymer_chains: ['rna']


denoiser:
  noise_scale_frame: 0.9
  noise_scale_ca: 0.9

diffuser:
  T: 50


scaffoldguided:
  scaffoldguided: True
  target_pdb: False
  target_path: null
  scaffold_list: null
  scaffold_dir: null
  sampled_insertion: 0
  sampled_N: 0
  sampled_C: 0
  ss_mask: 0
  systematic: False
  contig_crop: null
  radial_crop: null
  target_ss: null
  target_adj: null
  mask_loops: True
  target_ss_string: null
  target_ss_pairs: null
  ss_cond_ckpt_path: /home/afavor/git/RFD_AF/3template_na/rf_diffusion/train_session2023-11-21_1700601321.4267492/models/BFF_3.pt
  save_ss_matrix_png: False

  