# Base inference Configuration.

inference:
  input_pdb: test_data/1qys.pdb
  rfmotif: False
  num_designs: 10
  design_startnum: 0
  #ckpt_path: /mnt/home/jwatson3/for/nate/diffusion_models/BFF_wcomplexes_3epochs_072522.pt
  #ckpt_path: /mnt/home/davidcj/projects/BFF/rf_diffusion/checkpoints/train_session2022-08-12_1660310517.2802267/BFF_0.pt
  #ckpt_path: /mnt/net/databases/diffusion/models/Diff_t1d_31_t2d_47_082222_epoch19.pt
  #ckpt_path: /net/databases/diffusion/models/Diff_t1d_32_t2d_47_disp_fixed_finetuned_082622_epoch10.pt
  #ckpt_path: /net/databases/diffusion/models/Diff_rollback_epoch8.pt
  ckpt_path: /net/databases/diffusion/nate_tmp/new_SelfCond_crdscale0.25/models/BFF_4.pt
  ppi_design: False
  autogenerate_contigs: False
  symmetry: null
  recenter: True
  radius: 10.0
  model_only_neighbors: False
  num_recycles: 1
  recycle_schedule: null
  softmax_T: 1e-5
  output_prefix: samples/design
  scaffold_guided: False
  model_runner: NRBStyleSelfCond
  cautious: False
  recycle_between: False
  align_motif: True
  autoregressive_confidence: True
  no_confidence: True
  use_jw_selfcond: False
  symmetric_self_cond: True
  final_step: 1
  feed_true_xt: False
  annotate_termini: True
  deterministic: False
  zero_weights: False
  ligand: null
  internal_sym: null
  offset_scale: 1.0
  start_from_input: False
  subsymm_template: null 
  subsymm_t1d_perfect: False
  subsymm_template_xt_only: False
  subsymm_template_all_possible: True 
  input_xyz_t: False
  rigid_symm_motif: False
  initial_rigid_motif: False
  p2p_crop: -1
  rigid_repeat_motif: False
  n_repeats: 3
  origin_before_update: False
  two_template: False 
  three_template: False
  enforce_repeat_fit: False 
  rigid_fit_optim_steps: 12
  json_args: null 
  overrides: null 
  ij_visible: null
  motif_only_2d: False
  supply_motif_seq: False
  refine_recycles: -1
  refine: False
  chainbreak_chunks: True
  atomized_output: False
  contig_as_guidepost: False
  remove_guideposts_from_output: True
  mask_seq_by_polymer: False
  t2d_pic_filename: null # DELETE NOT USED
  save_motif_t2d_png: False
  num_atoms_modeled: 14
  num_atoms_saved: 23
  save_rna_oneletter: False
  set_diffused_prot_to: 'ALA'
  set_diffused_dna_to: null
  set_diffused_rna_to: null
  # ema: True

contigmap:
  contigs: ['20', 'A3-23', '30']
  inpaint_str: null
  inpaint_seq: null
  length: null
  polymer_chains: null
  use_old_receptor_system: True


model:
  n_extra_block: 4
  n_main_block: 32
  n_ref_block: 4
  d_msa: 256
  d_msa_full: 64
  d_pair: 128
  d_templ: 64
  d_templ_1d: null
  d_templ_2d: null
  n_head_msa: 8
  n_head_pair: 4
  n_head_templ: 4
  d_hidden: 32
  d_hidden_templ: 32
  p_drop: 0.15
  SE3_param:
    num_layers: -1
    num_channels: -1
    num_degrees: -1
    n_heads: -1
    div: -1
    l0_in_features: -1
    l0_out_features: -1
    l1_in_features: -1
    l1_out_features: -1
    num_edge_features: -1
  SE3_ref_param:
    n_extra_block: -1
    n_main_block: -1
    n_ref_block: -1
    n_finetune_block: -1
    d_msa: -1
    d_msa_full: -1
    d_pair: -1
    d_templ: -1
    n_head_msa: -1
    n_head_pair: -1
    n_head_templ: -1
    d_hidden: -1
    d_hidden_templ: -1
    p_drop: -1
    use_extra_l1: -1
    use_atom_frames: -1
    freeze_track_motif: -1
  freeze_track_motif: False
  symmetrize_repeats: False
  repeat_length: null
  symmsub_k: null
  sym_method: mean
  copy_main_block_template: False
  main_block: null 
  symm_fit_start: -1
  clash: 4.0
  lock_symmsubs_at: -1
  allow_particle_recenter: false 
  # half_precision: False

diffuser:
  T: 200
  b_0: 1e-2
  b_T: 7e-2
  schedule_type: linear
  so3_type: igso3
  eucl_type: standard
  aa_decode_steps: 40
  chi_type: wrapped_normal
  crd_scale: 0.0667
  schedule_kwargs: {}
  partial_T: null    
  so3_schedule_type: linear
  min_b: 1.5
  max_b: 2.5
  min_sigma: 0.02
  max_sigma: 1.5

seq_diffuser:
  s_b0: null
  s_bT: null
  schedule_type: null
  loss_type: null
  seqdiff: null

denoiser:
  noise_scale_ca: 1
  noise_scale_frame: 1
  noise_scale_torsion: 1

ppi:
  hotspot_res: null
  binderlen: null

potentials:
  guiding_potentials: null 
  guide_scale: 10
  guide_decay: constant
  olig_inter_all : null
  olig_intra_all : null
  olig_custom_contact : null

contig_settings:
  ref_idx: null
  hal_idx: null
  idx_rf: null
  inpaint_seq_tensor: null
  inpaint_str_tensor: null


preprocess:
  sidechain_input: False
  motif_sidechain_input: True
  na_sidechain_input: True
  sequence_decode: True
  d_t1d: 22
  d_t2d: 44
  show_poly: False
  prob_self_cond: 0.0
  str_self_cond: False
  seq_self_cond: False
  predict_previous: False
  eye_frames: False 
  randomize_frames: False
  num_atoms_na: 14
  motif_only_2d: False
  # num_atoms_input: 14

scaffoldguided:
  scaffoldguided: False
  target_pdb: False
  target_path: null
  scaffold_list: null
  scaffold_dir: null
  sampled_insertion: 0
  sampled_N: 0
  sampled_C: 0
  ss_mask: 0
  systematic: False
  contig_crop: null
  radial_crop: null
  target_ss: null
  target_adj: null
  mask_loops: True
  target_ss_string: null
  target_ss_pairs: null
  target_ss_pair_ori: null
  force_loops_list: null
  force_multi_contacts: null
  ss_cond_ckpt_path: /projects/ml/afavor/RFD/models/all_na_ss_cond/train_session2023-11-23_1700767971.921231_BFF_3.pt

  
logging:
  inputs: False
