defaults:
  - aa

inference:
  num_designs: 1
  design_startnum: -1
  output_prefix: debug/gaa
  model_runner: NRBStyleSelfCond
  input_pdb: '/home/ahern/projects/dev_rf_diffusion/benchmark/input/gaa.pdb'
  ligand: 'UNL'

contigmap:
  contigs: ['A100-100,1-1']
  length: 2-2

