# Base inference Configuration.
defaults:
  - multi_polymer

inference:
  ckpt_path: /projects/ml/afavor/RFD/models/all_na_ss_cond/train_session2023-12-15_1702680088_BFF_4.pt
  use_poly_hotspots_t1d: False
