defaults:
  - debug

inference:
  output_prefix: debug/partial_small_complete
  model_runner: NRBStyleSelfCond
  input_pdb: 'test_data/sc_native.pdb'

diffuser:
  partial_T: 10

contigmap:
  contigs: ['10,A11-70']
  length: 70-70

