defaults:
  - asym_multi


inference:
  input_pdb: test_data/1qys.pdb
  rfmotif: True
  align_motif: False

rfmotif:
  regions: null
  pdbs: null
  pointsyms: null
  flip: False
  fit_only_junctions: 0
  region_fudge_factor: 0
  dump_debug_pdbs: False
  motif_occlusion_weight: 0.0
  motif_occlusion_dist: 13.0
  float_seq_pos: True
  fit_at_t: 15
  motif_fit_tsteps: null
  
